name: Build image and Push
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      VERSION: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push
      run: |
        docker build . --file Dockerfile --tag ghcr.io/uniamerica/unijobs-front:$VERSION
        echo ${{secrets.CR_PAT}} | docker login https://ghcr.io -u JonasXPX --password-stdin 
        docker push ghcr.io/uniamerica/unijobs-front:$VERSION
